function admin(){return !!guard("admin")}
function dashboard(){if(!document.getElementById("doctorsStat")||!admin())return;const a=appointments();document.getElementById("doctorsStat").textContent=doctors().length;document.getElementById("usersStat").textContent=users().filter(u=>u.role==="user").length;document.getElementById("appointmentsStat").textContent=a.length;document.getElementById("confirmedStat").textContent=a.filter(x=>x.status==="Confirmed").length;document.getElementById("recent").innerHTML=a.length?table(a.slice(-5).reverse(),false):'<div class="empty">No appointments yet.</div>'}
function doctorTable(){const box=document.getElementById("doctorTable");if(!box||!admin())return;box.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Doctor</th><th>Specialization</th><th>Experience</th><th>Fee</th><th>Days</th><th>Actions</th></tr></thead><tbody>${doctors().map(d=>`<tr><td>${d.name}</td><td>${d.specialty}</td><td>${d.experience}</td><td>${money(d.fee)}</td><td>${d.days}</td><td><button class="btn outline small" onclick="editDoctor(${d.id})">Edit</button> <button class="btn danger small" onclick="deleteDoctor(${d.id})">Delete</button></td></tr>`).join("")}</tbody></table></div>`}
function resetForm(){document.getElementById("doctorForm").reset();document.getElementById("doctorId").value="";document.getElementById("formTitle").textContent="Add Doctor"}
function editDoctor(id){const d=doctors().find(x=>x.id===id);if(!d)return;document.getElementById("formPanel").classList.remove("hidden");document.getElementById("formTitle").textContent="Edit Doctor";for(const [id,val] of [["doctorId",d.id],["doctorName",d.name],["doctorSpecialty",d.specialty],["experience",d.experience],["fee",d.fee],["days",d.days],["about",d.about]])document.getElementById(id).value=val}
function saveDoctor(e){e.preventDefault();const arr=doctors(),id=Number(document.getElementById("doctorId").value),d={id:id||Date.now(),name:document.getElementById("doctorName").value,specialty:document.getElementById("doctorSpecialty").value,experience:document.getElementById("experience").value,fee:Number(document.getElementById("fee").value),days:document.getElementById("days").value,about:document.getElementById("about").value,emoji:"🩺"};const i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=d;else arr.push(d);set(KEY.doctors,arr);document.getElementById("formPanel").classList.add("hidden");resetForm();doctorTable();alert("Doctor saved successfully.")}
function deleteDoctor(id){if(confirm("Delete this doctor?")){set(KEY.doctors,doctors().filter(d=>d.id!==id));doctorTable()}}
function userTable(){const b=document.getElementById("userTable");if(!b||!admin())return;const a=users().filter(u=>u.role==="user");b.innerHTML=a.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Role</th></tr></thead><tbody>${a.map(u=>`<tr><td>${u.id}</td><td>${u.name}</td><td>${u.email}</td><td>User</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">No users registered.</div>'}
function table(arr,full=true){return `<div class="table-wrap"><table><thead><tr><th>ID</th><th>Patient</th><th>Doctor</th><th>Date</th><th>Status</th>${full?"<th>Action</th>":""}</tr></thead><tbody>${arr.map(a=>`<tr><td>${a.id}</td><td>${a.userName}</td><td>${a.doctorName}</td><td>${a.date}<br>${a.time}</td><td><span class="status status-${a.status}">${a.status}</span></td>${full?`<td><select onchange="updateStatus('${a.id}',this.value)">${["Pending","Confirmed","Completed","Cancelled"].map(s=>`<option ${s===a.status?"selected":""}>${s}</option>`).join("")}</select></td>`:""}</tr>`).join("")}</tbody></table></div>`}
function appointmentTable(){const b=document.getElementById("appointmentTable");if(!b||!admin())return;const a=appointments().reverse();b.innerHTML=a.length?table(a):'<div class="empty">No appointments.</div>'}
function updateStatus(id,status){const a=appointments(),x=a.find(v=>v.id===id);if(x)x.status=status;set(KEY.appointments,a);appointmentTable()}
document.addEventListener("DOMContentLoaded",()=>{dashboard();doctorTable();userTable();appointmentTable();const add=document.getElementById("addDoctor");if(add)add.onclick=()=>{resetForm();document.getElementById("formPanel").classList.remove("hidden")};const cancel=document.getElementById("cancel");if(cancel)cancel.onclick=()=>document.getElementById("formPanel").classList.add("hidden");const form=document.getElementById("doctorForm");if(form)form.onsubmit=saveDoctor})
